# Generated by Django 2.1.7 on 2019-02-17 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_character_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='char_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='characters.Class'),
        ),
    ]
