# Generated by Django 2.1.7 on 2019-02-17 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_auto_20190217_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='char_class',
            field=models.ForeignKey(default='Select a character class', on_delete=django.db.models.deletion.CASCADE, to='characters.Class'),
        ),
    ]
