# Generated by Django 2.1.7 on 2019-02-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_auto_20190217_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.BinaryField(blank=True),
        ),
    ]
