# Generated by Django 2.1.7 on 2019-02-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0007_auto_20190217_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.ImageField(blank=True, default='media/human.jpg', upload_to=''),
        ),
    ]
