# Generated by Django 2.1.7 on 2019-02-19 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_auto_20190219_1732'),
        ('characters', '0018_auto_20190218_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='entries',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='journal.Post'),
        ),
    ]
