# Generated by Django 2.1.7 on 2019-02-19 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0019_character_entries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='entries',
        ),
    ]
