# Generated by Django 2.1.7 on 2019-02-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0020_remove_character_entries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
