# Generated by Django 2.1.7 on 2019-02-21 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0023_auto_20190220_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=14, null=True, unique=True),
        ),
    ]
