# Generated by Django 2.1.7 on 2019-02-21 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0025_auto_20190221_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='character',
            name='level',
        ),
    ]
