# Generated by Django 2.1.7 on 2019-02-22 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0026_auto_20190221_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, default=0, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='enemy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.Enemy'),
        ),
    ]
