# Generated by Django 2.1.7 on 2019-02-23 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0027_auto_20190222_0430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enemy',
            options={'verbose_name_plural': 'Enemies'},
        ),
    ]
