# Generated by Django 2.1.7 on 2019-02-19 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('characters', '0018_auto_20190218_2146'),
        ('journal', '0002_auto_20190218_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='character',
            field=models.ForeignKey(db_column='', on_delete=django.db.models.deletion.CASCADE, to='characters.Character'),
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('user', 'character')},
        ),
    ]
