# Generated by Django 2.1.7 on 2019-02-19 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_auto_20190219_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.Character'),
        ),
    ]
