# Generated by Django 2.1.7 on 2019-02-16 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='info',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
