# Generated by Django 2.1.7 on 2019-02-23 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190216_0515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='info',
        ),
    ]
